controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


modifications_informations:
    path: /modifications-informations
    controller: App\Controller\ModificationsInformationsController::index

dashboard:
    path: /dashboard
    controller: App\Controller\Admin\DashboardController::index
    
