controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

modifications_informations:
    path: /modifications-informations
    controller: App\Controller\ModificationsInformationsController::index

dashboard:
    path: /dashboard
    controller: App\Controller\Admin\DashboardController::index

app_profil:
    path: /profil
    controller: App\Controller\ProfilController::index

app_user_delete:
    path: /users/{id}
    methods: ['DELETE']
    controller: App\Controller\UserController::delete
    requirements:
        id: '\d+'

app_annonce_donner_modifier:
    path: /annonce-donner-modifier/{id}
    controller: App\Controller\AnnonceDonnerModifierController::edit
    requirements:
        id: '\d+'

app_annonce_chercher_modifier:
    path: /annonce-chercher-modifier/{id}
    controller: App\Controller\AnnonceChercherModifierController::edit
    requirements:
        id: '\d+'

announce_delete:
    path: /announces/{id}
    methods: ['DELETE']
    controller: App\Controller\MesAnnoncesController::delete
    
app_profil_upload_avatar:
    path: /profil/upload-avatar
    methods: [POST]
    controller: App\Controller\ProfilController::uploadPhoto

app_annonce_chercher:
    path: /annonce-chercher
    controller: App\Controller\AnnonceChercherController::index
    
app_rechercher:
    path: /rechercher
    controller: App\Controller\RechercherController::search

